Repository ESMValGroup/ESMValTool_Tutorial, pull requests merged in 2021-03, with the labels that each got.

#195 Fixed broken link to example recipe in lesson 4
  _episodes/04-recipe.md
Labels: bug

#185 Add episode on how to write your own diagnostics
  _episodes/10-diagnostics.md
Labels: lesson

#194 Add brief summary of possible ways to use ESMValTool
  _episodes/02-installation.md
Labels: enhancement, lesson
